### ISSUE TITLE
pcdm: autologin broke

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1433]
pcdm autologin isn't working for me with both Lumina and MATE with the timeout set to 0 seconds. I think it tries but fails and you end up having to login manually.

Also, why do I not see an icon to configure PCDM in the control panel? To enable autologin I had to run `pc-su pc-dmconf` from the terminal.

**Comment by danboid** [comment]
I have tried this again since the recent update but auto login is still broken.

I have seen other users reporting having the same probs on discourse https://discourse.trueos.org/t/autologin-not-working/1444

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/pcdm/commit/de4d11dc39d2c73ef95b103ce269ed6c554ce4d8

**Comment by danboid** [comment]
I've just updated TrueOS (to Lumina 1.2.2) and autologin is still broken.

**Comment by ctuffli** [comment]
Autologin doesn't work for me either. Did this commit make it into the stable build:
```OS git branch ……………………………………………………………………………………… trueos-stable
OS git revision ………………………………………………………………………………… ac2f0aa3b
OS kernel build time ………………………………………………………… Wed 2017 Jun 21 01:09:23 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201706210948```
