### ISSUE TITLE
automounter broken in TrueOS unstable 201707111911

### ISSUE THREAD

**Issue by asomers** [trueos/trueos-core#1482]
After upgrading TrueOS unstable to TrueOS-Desktop-201707111911, the automounter is broken with both USB drives and NFSv3 shares.  Attempting to access /net/<SERVERNAME>/<SHARENAME> hangs, and /var/log/messages fills up with lines like the following:
```
Sep 19 21:11:19  kernel: WARNING: autofs_task: request 93 for /net/ timed out after 30 seconds
Sep 19 21:11:19  kernel: WARNING: autofs_trigger_one: request for /net/ completed with error 60
```
Attempting to access /media/GARMIN_da0 hangs, and /var/log/messages fills up with stuff like:
```
Sep 19 21:12:53  kernel: WARNING: autofs_task: request 101 for /autofs/ timed out after 30 seconds
Sep 19 21:12:53  kernel: WARNING: autofs_trigger_one: request for /autofs/ completed with error 60
```

```
> about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170919_064223 NR 2017-09-19
       after restart (R) … 12.0-CURRENT-up-20170919_064223 NR 2017-09-19
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    number of cores ……………… 8
host ……………………………………………………… threonine.lauralan.noip.me
memory ………………………………………………… 16384 MB available, 13470 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… 075edd7be
OS kernel build time ………………………………………………………… Mon 2017 Sep 18 15:04:04 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… EDGE
TrueOS version …………………………… TrueOS-Desktop-201707111911
uptime ………………………………………………… 1:40
user  …………………………………………………… somers

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <NVIDIA (0x0072) (HDMI/DP 8ch)> (play) default
    wireless driver ……………… 
    X11 drivers ………………………… nvidia_drv.so
```

**Comment by beanpole135** [comment]
This is fixed in the latest UNSTABLE images.

**Comment by asomers** [comment]
This is still happening on TrueOS 12.0-CURRENT-up-20171017_220150, for both NFS and USB drives.

**Comment by asomers** [comment]
Still happening at 20171023_231157 .  I'll open a new issue, since I'm unable to reopen old ones.
