### ISSUE TITLE
Booting PAUSE on Intel NUC DN2820FYKH & latest TrueOS.

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#241]
Intel NUC DN2820FYKH second revision with CPU Intel N2830. Latest Bios at this time. Issue: On NUC 2820 2-nd rev. is PAUSE on booting process. On NUC5PPYH there is no this problem.

Screenshot:

![nuc2830](https://cloud.githubusercontent.com/assets/20837310/21418228/f6e90ea8-c849-11e6-9009-e00b1e7302c3.jpg)

Video: latest TrueOS case and NUC DN2820FYKH (the problem is observed): https://yadi.sk/i/OJK41wWM34Na38

Video: latest TrueOS case and NUC5PPYH. (no problem): https://yadi.sk/i/W4lYKnAS34NaBC

Its recommended to download the videos and watch it in video player, but dont watch online.

**Comment by pkgdemon** [comment]
Fixed in:

https://github.com/trueos/trueos-core/commit/5d1c10293315dab2d5770f6337d5f13f391d5943

This was caused by the splash getting turned on with boot_mute.  On some systems where the splash cannot be rendered it will cause this.  Until we have a way for the user to turn it off we are leaving it off for now.

**Comment by DmitryPostolov** [comment]
The problem is not solved. ;-(( Do you need the video fo new TrueOS image?

[dmitry@trueos772] ~% uname -a
FreeBSD trueos772.local 12.0-CURRENT FreeBSD 12.0-CURRENT #20 3dbce2a(drm-next): Sat Jan 21 13:48:35 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by q5sys** [comment]
I just installed TrueOS on that exact same NUC a day ago and it works
fine.  What type of pause are you getting?

[q5sys@trueos-nuc] ~% about
[: =: unexpected operator
  ______                   ____  _____
 /_  __/______  _____     / __ \/ ___/
  / / / ___/ / / / _ \   / / / /\__ \
 / / / /  / /_/ /  __/  / /_/ /___/ /
/_/ /_/   \__,_/\___/   \____//____/

General info:
       Host:...............trueos-nuc
       User:...............q5sys
       Uptime:.............1 day, 15:54
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....3dbce2a
       TrueOS ver:.........TrueOS-Desktop-201701261715
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz
       CPU cores:..........2
       Memory (free/avail):6229 / 8192 Mb
       Package set:........STABLE
       Desktop environment:Lumina
       X11 Driver:.........modesetting_drv.so
       OSS Driver:.........pcm0: <Realtek (0x0283) (Left Analog)>
(play/rec) default
       WIFI Driver:........iwm0
[q5sys@trueos-nuc] ~% uname -a
FreeBSD trueos-nuc 12.0-CURRENT FreeBSD 12.0-CURRENT #20 3dbce2a(drm-next):
Sat Jan 21 13:48:35 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC
 amd64
[q5sys@trueos-nuc] ~%

**Comment by DmitryPostolov** [comment]
Now I am make the video and get the statistics. I am think that this is FreeBSD bugs ported to TrueOS or DragonFlyBSD or bug in latest Bios/Uefi cooperating, or hardware problem.

Bugreport for DragonFly BSD: http://lists.dragonflybsd.org/pipermail/users/2017-January/313213.html

**Comment by pkgdemon** [comment]
@q5sys You appear to be using BIOS boot from your about output?  @DmitryPostolov In his first screenshot was using EFI.  This looked like boot_mute behavior but maybe it is not.

**Comment by q5sys** [comment]
Joe, when I cycle the unit tomorrow I'll try using EFI.  I had to use BIOS
so I could get it to boot off the USB stick to install, I forgot that I
didnt change it back.

**Comment by DmitryPostolov** [comment]
[dmitry@trueos772] ~% about
[: efifb: unexpected operator
  ______                   ____  _____
 /_  __/______  _____     / __ \/ ___/ 
  / / / ___/ / / / _ \   / / / /\__ \ 
 / / / /  / /_/ /  __/  / /_/ /___/ / 
/_/ /_/   \__,_/\___/   \____//____/  

General info:
       Host:...............trueos772.local
       User:...............dmitry
       Uptime:.............50 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....3dbce2a
       TrueOS ver:.........TrueOS-Desktop-201701261715
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz
       CPU cores:..........2
       Memory (free/avail):2291 / 4096 Mb
       Package set:........STABLE
       Desktop environment:Lumina
       X11 Driver:.........modesetting_drv.so 
       OSS Driver:.........pcm1: <Intel (0x2882) (HDMI/DP 8ch)> (play) default
       WIFI Driver:........iwm0

**Comment by DmitryPostolov** [comment]
Any ideas about this 15 secs pause on booting process?

**Comment by DmitryPostolov** [comment]
This problem is not solved. :-(
