### ISSUE TITLE
Can't login to GUI unless Full Name == Username

### ISSUE THREAD

**Issue by jradxl** [trueos/trueos-core#269]
In version, TrueOS-Desktop-2016-12-27-x64-DVD
Once installed (i'm using VirtualBox) I get Username and Password invalid message when setting a reasonable Full Name. Once I change Full Name == Username, then I can log in.
Wrong field being used??

**Comment by jungle-boogie** [comment]
full name = jungle boogie
username = jungleboogie

I would expect that you can only login with the username. Does the login screen ask for a full name, username or login?

**Comment by pkgdemon** [comment]
Does it make any difference is full name is "Jungle Boogie" with uppercase letters?

**Comment by jradxl** [comment]
The Login dialogue shows the FullName, and the user needs to select. Suggest the software is using that as the Username.

**Comment by pkgdemon** [comment]
Can you by chance attach a screenshot?

**Comment by jradxl** [comment]
![john2](https://cloud.githubusercontent.com/assets/1639936/21663396/d9318122-d2d7-11e6-9c11-af0a44b85d8a.png)
![john1](https://cloud.githubusercontent.com/assets/1639936/21663397/d93b8c80-d2d7-11e6-93fd-70d83494c365.png)

First and Last work (Full Name is same as Username)
Middle two dont

**Comment by jradxl** [comment]
![john2](https://cloud.githubusercontent.com/assets/1639936/21663545/c49f8b22-d2d8-11e6-8c51-acb0b3525977.png)
![john1](https://cloud.githubusercontent.com/assets/1639936/21663544/c4991ac6-d2d8-11e6-9da9-cc8f21e5d358.png)

First and Last work (Fullname == Username)
Middle two don't

**Comment by pkgdemon** [comment]
Ah now I now I understand.  I think I ran into this as well trying to do Joe (home), and Joe (work)

**Comment by pkgdemon** [comment]
Seems to be working with adduser, and console login.  I suspect the issue may be something related to PCDM.

**Comment by grahamperrin** [comment]
Cross reference, in PC-BSD forums: 

- [Cannot login to TrueOs after install as Guest in VirtualBox](https://forums.pcbsd.org/thread-21128.html)

**Comment by beanpole135** [comment]
I think I just fixed this in PCDM[1]:
The "findUser()" routine was expecting a displayname as input, but I made it also accept a username too.

https://github.com/trueos/pcdm/commit/79b4e4e8da33d4f47d5ca3dbdfcf97f16293ea25

**Comment by CoryAlbrecht** [comment]
Still happens on a brand new TrueOS install from an image downloaded today.
